#!/usr/bin/env bash
# backend.sh — Point the codex or claude actor at any OpenAI/Anthropic-compatible
# endpoint. Writes <SKILL_DIR>/.<actor>_env.local (gitignored), which
# {codex,claude}_turn.sh source before invoking the CLI.
#
# Usage:
#   backend.sh codex  <base-url> <api-key> [default-model]
#   backend.sh claude <base-url> <api-key> [opus-model] [sonnet-model] [haiku-model]
#   backend.sh show   [codex|claude]
#   backend.sh clear  <codex|claude>
#
# Examples:
#   # Codex → official OpenAI:
#   backend.sh codex https://api.openai.com/v1 sk-... gpt-4o
#
#   # Codex → cialloapi proxy:
#   backend.sh codex https://api.cialloapi.cn/v1 sk-... gpt-5.5
#
#   # Claude → official Anthropic:
#   backend.sh claude https://api.anthropic.com sk-ant-... claude-opus-4-5
#
#   # Claude → DeepSeek Anthropic-compat (single model for all tiers):
#   backend.sh claude https://api.deepseek.com/anthropic sk-... deepseek-v4-pro[1m]

set -euo pipefail
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"

_usage() { sed -n '/^# backend\.sh/,/^[^#]/{ /^[^#]/d; s/^# \{0,1\}//; p; }' "$0"; }

case "${1:-}" in
  -h|--help|"") _usage; exit 0;;
esac

cmd="$1"; shift

_show_one() {
  local actor="${1:-}"
  local f="${SKILL_DIR}/.${actor}_env.local"
  if [[ -r "$f" ]]; then
    printf '── %s (%s) ──\n' "$actor" "$f"
    grep -E '^export [A-Z_]+=' "$f" | sed -E 's/(TOKEN|API_KEY)=.*/\1=***redacted***/'
  else
    printf '── %s: not configured (no %s) ──\n' "$actor" "$f"
  fi
}

case "$cmd" in
  show)
    if [[ $# -gt 0 ]]; then _show_one "$1"; else _show_one codex; echo; _show_one claude; fi
    exit 0
    ;;
  clear)
    actor="${1:?which actor: codex|claude}"
    rm -f "${SKILL_DIR}/.${actor}_env.local"
    echo "cleared ${SKILL_DIR}/.${actor}_env.local"
    exit 0
    ;;
  codex)
    base_url="${1:?missing base-url}"; api_key="${2:?missing api-key}"
    default_model="${3:-}"
    out="${SKILL_DIR}/.codex_env.local"
    {
      printf '# Auto-generated by scripts/backend.sh on %s. Edit or rerun to change.\n' "$(date -u +%FT%TZ)"
      printf 'export OPENAI_BASE_URL=%q\n' "$base_url"
      printf 'export OPENAI_API_KEY=%q\n'  "$api_key"
      [[ -n "$default_model" ]] && printf 'export OPENAI_DEFAULT_MODEL=%q\n' "$default_model"
    } > "$out"
    chmod 600 "$out"
    echo "wrote $out (chmod 600)"
    ;;
  claude)
    base_url="${1:?missing base-url}"; auth_token="${2:?missing api-key}"
    opus="${3:-}"; sonnet="${4:-${opus}}"; haiku="${5:-${opus}}"
    out="${SKILL_DIR}/.claude_env.local"
    {
      printf '# Auto-generated by scripts/backend.sh on %s. Edit or rerun to change.\n' "$(date -u +%FT%TZ)"
      printf 'export ANTHROPIC_BASE_URL=%q\n'   "$base_url"
      printf 'export ANTHROPIC_AUTH_TOKEN=%q\n' "$auth_token"
      if [[ -n "$opus" ]]; then
        printf 'export ANTHROPIC_MODEL=%q\n'                 "$opus"
        printf 'export ANTHROPIC_DEFAULT_OPUS_MODEL=%q\n'    "$opus"
        printf 'export ANTHROPIC_DEFAULT_SONNET_MODEL=%q\n'  "$sonnet"
        printf 'export ANTHROPIC_DEFAULT_HAIKU_MODEL=%q\n'   "$haiku"
        printf 'export CLAUDE_CODE_SUBAGENT_MODEL=%q\n'      "$haiku"
      fi
    } > "$out"
    chmod 600 "$out"
    echo "wrote $out (chmod 600)"
    ;;
  *)
    echo "unknown command: $cmd" >&2
    _usage >&2
    exit 2
    ;;
esac
