#!/usr/bin/env python3
"""Recompute `ROLE_TOKEN_BUDGETS` from observed turn usage and (optionally)
rewrite the constants block in `scripts/lib/estimate_cost.py`.

Default behaviour: print a side-by-side diff of current vs proposed budgets
along with sample sizes; the human commits the change. With `--apply`, the
constants block (between sentinel comments) is rewritten in-place; the prior
table is preserved as a comment-out history block immediately below.

Workflow (quarterly):
  1. Run dispatches as normal — wrappers append to `.roundtable/usage.log`.
  2. After ~30 days: `python3 scripts/recalibrate_token_budgets.py --since-days 30`
  3. Review diff; if good: re-run with `--apply`.
  4. `git diff scripts/lib/estimate_cost.py` — should show only the budget
     block + a dated `# NOTE` line. Commit on its own.

Min-samples: cells with < 5 observations are *not* overwritten and the diff
warns. This prevents a single noisy turn from flipping a budget.

Stdlib only.
"""
from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

_HERE = pathlib.Path(__file__).resolve().parent / "lib"
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import estimate_cost as ec  # noqa: E402  (relies on sys.path tweak above)
import usage_log  # noqa: E402

ESTIMATE_FILE = _HERE / "estimate_cost.py"
BEGIN = "# BEGIN_AUTOGEN_ROLE_TOKEN_BUDGETS"
END = "# END_AUTOGEN_ROLE_TOKEN_BUDGETS"


def _format_table(suggested: dict, current: dict, metadata: dict) -> str:
    """Render a compact role × bucket comparison table."""
    headers = ("role", "input(cur→new)", "out_chat", "out_thinking", "n_in/n_chat/n_think")
    rows: list[tuple[str, ...]] = []
    for role, cur in current.items():
        new = suggested.get(role, cur)
        meta = metadata.get(role, {})

        def cell(field: str, kept_flag: str) -> str:
            cv, nv = cur[field], new[field]
            mark = "*" if meta.get(kept_flag) else " "
            if cv == nv:
                return f"{cv:>7,d}{mark}"
            return f"{cv:>7,d}→{nv:>7,d}{mark}"

        rows.append(
            (
                role,
                cell("input", "input_kept_current"),
                cell("output_chat", "chat_kept_current"),
                cell("output_thinking", "thinking_kept_current"),
                f"{meta.get('n_input', 0)}/{meta.get('n_chat_out', 0)}/{meta.get('n_think_out', 0)}",
            )
        )

    widths = [
        max(len(headers[i]), *(len(r[i]) for r in rows)) for i in range(len(headers))
    ]
    sep = "  ".join("-" * w for w in widths)
    out_lines = [
        "  ".join(h.ljust(widths[i]) for i, h in enumerate(headers)),
        sep,
    ]
    for r in rows:
        out_lines.append("  ".join(c.ljust(widths[i]) for i, c in enumerate(r)))
    out_lines.append(
        "* = sample below min-samples threshold; cell kept at current (not overwritten)."
    )
    return "\n".join(out_lines)


def _format_budgets_block(budgets: dict, *, sample_metadata: dict, since_days: int | None) -> str:
    """Render the new constants block (between BEGIN/END sentinels)."""
    today = datetime.date.today().isoformat()
    n_rows = sum(meta.get("n_input", 0) for meta in sample_metadata.values())
    window = f"--since-days={since_days}" if since_days else "all-time"
    lines = [
        BEGIN,
        f"# NOTE [{today}]: regenerated by recalibrate_token_budgets.py",
        f"#   window={window}  total_input_observations={n_rows}",
        "#   per-role sample sizes follow each row as `# n=<int>`.",
        "ROLE_TOKEN_BUDGETS: dict[str, dict[str, int]] = {",
    ]
    for role, b in budgets.items():
        meta = sample_metadata.get(role, {})
        n_marker = (
            f"# n_in={meta.get('n_input', 0)}, "
            f"n_chat={meta.get('n_chat_out', 0)}, "
            f"n_think={meta.get('n_think_out', 0)}"
        )
        lines.append(
            f'    "{role}":'
            + " " * max(1, 22 - len(role) - 2)
            + "{"
            + f'"input": {b["input"]:>6_d}, '
            + f'"output_chat": {b["output_chat"]:>5_d}, '
            + f'"output_thinking": {b["output_thinking"]:>5_d}'
            + f"}},  {n_marker}"
        )
    lines.append("}")
    lines.append(END)
    return "\n".join(lines)


def _rewrite_estimate_cost(new_block: str) -> tuple[bool, str]:
    """Replace the BEGIN/END block in estimate_cost.py.

    Returns (changed, diff_summary_text). If sentinels are missing we
    insert them around the existing literal `ROLE_TOKEN_BUDGETS = {…}` block
    on first apply, leaving the original definition commented-out below.
    """
    src = ESTIMATE_FILE.read_text(encoding="utf-8")

    if BEGIN in src and END in src:
        pattern = re.compile(
            r"^" + re.escape(BEGIN) + r".*?^" + re.escape(END) + r"$",
            re.DOTALL | re.MULTILINE,
        )
        new_src, n = pattern.subn(new_block, src, count=1)
        if n != 1:
            return False, "BEGIN/END sentinels found but regex match failed; aborting."
        ESTIMATE_FILE.write_text(new_src, encoding="utf-8")
        return True, "in-place rewrite via existing sentinels."

    # First-run path: wrap the literal table.
    pattern = re.compile(
        r"^ROLE_TOKEN_BUDGETS:\s*dict\[str,\s*dict\[str,\s*int\]\]\s*=\s*\{.*?^\}",
        re.DOTALL | re.MULTILINE,
    )
    match = pattern.search(src)
    if not match:
        return False, "Could not locate ROLE_TOKEN_BUDGETS literal in estimate_cost.py."
    original = match.group(0)
    commented = "\n".join("# " + line for line in original.splitlines())
    today = datetime.date.today().isoformat()
    replacement = (
        new_block
        + "\n\n"
        + f"# Prior ROLE_TOKEN_BUDGETS (kept for audit; replaced {today} by recalibrate_token_budgets.py):\n"
        + commented
    )
    new_src = src[: match.start()] + replacement + src[match.end() :]
    ESTIMATE_FILE.write_text(new_src, encoding="utf-8")
    return True, "first-run wrap: previous definition commented-out below sentinels."


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--since-days",
        type=int,
        default=None,
        help="Filter usage records by recency (default: all-time).",
    )
    parser.add_argument(
        "--diff-only",
        action="store_true",
        help="Print only the budget diff, skip the proposed-block preview.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help=(
            "Rewrite scripts/lib/estimate_cost.py. Without this flag the script "
            "is read-only — only prints the proposed change."
        ),
    )
    parser.add_argument(
        "--log",
        default=None,
        help="Override path to usage.log (default: $ROUNDTABLE_PROJECT_ROOT/.roundtable/usage.log).",
    )
    parser.add_argument(
        "--min-samples",
        type=int,
        default=5,
        help="Min observations per cell before overwriting (default 5).",
    )
    args = parser.parse_args(argv)

    try:
        records = usage_log.read_usage_log(args.log, since_days=args.since_days)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if not records:
        print(
            "No usage records found. Run dispatches first; the wrapper hooks in "
            "codex_turn.sh / claude_turn.sh write to $ROUNDTABLE_PROJECT_ROOT/.roundtable/usage.log.",
            file=sys.stderr,
        )
        return 1

    result = usage_log.recalibrate_role_budgets(
        records,
        ec.ROLE_TOKEN_BUDGETS,
        min_samples=args.min_samples,
    )
    suggested = result["budgets"]
    metadata = result["metadata"]

    print(
        f"# usage records: {len(records)}  window={args.since_days or 'all-time'}  "
        f"min_samples={args.min_samples}"
    )
    print(_format_table(suggested, ec.ROLE_TOKEN_BUDGETS, metadata))

    new_block = _format_budgets_block(
        suggested, sample_metadata=metadata, since_days=args.since_days
    )
    if not args.diff_only:
        print()
        print("# Proposed estimate_cost.py block:")
        print(new_block)

    if args.apply:
        changed, msg = _rewrite_estimate_cost(new_block)
        if changed:
            print(f"\nApplied: {msg} ({ESTIMATE_FILE})")
            return 0
        print(f"\nFAILED to apply: {msg}", file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
